# Generated by Django 4.1.4 on 2022-12-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_order_address_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="status", field=models.BooleanField(default=False),
        ),
    ]
